name: Python CI
on:
 push:
    branches: [main]
jobs:
  build:
     run-on: self-hosted
    
     steps:
       - name: Checkout code
         uses: actions/checkout

       - name: Run Python Script
         run: python app.py
