name: Python CI
on:
 push:
    branches: [main]
jobs:
  build:
     runs-on: self-hosted
    
     steps:
       - name: Checkout code
         uses: actions/checkout@v4

       - name: Run Python Script
         run: python3 Hello.py
